analytics: {}
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.600216
  lightness: 0.295608
  rhythmicContrast: 0.917698
  saturation: 0.765202
cta: {}
layout_spectrum: 0.3930861945955416
name: daria
opengraph: {}
purpose: {}
typography_spectrum: 0.4165073972508666
